# Numpy

- Numerical python
- import numpy as np (사실상의 표준)**굵은 텍스트**

In [3]:
import numpy as np

In [4]:
a = [1, 2, 3]
a * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [5]:
b = np.array([1,2,3])
b * 3

array([3, 6, 9])

## 1. Numpy Dimensional array

- numpy 는 np.array 함수를 활용하여 배열을 생성함 -> ndarray
- numpy 는 하나의 데이터 타입만 배열에 넣을 수 있음
- List 와 가장 큰 차이점 , Dynamic 예 , [1, 2, “5”, 4.2]) not supported
- C 의 Array 를 사용하여 배열을 생성함

In [6]:
a = np.array([1,4,5,8], float)
a

array([1., 4., 5., 8.])

In [7]:
type(a)

numpy.ndarray

In [8]:
a.dtype, a.shape

(dtype('float64'), (4,))


## 2. Array shape

- Vector 1차원
  test_array= np.array ([1, 4, 5, 8], dtype=)
- Matrix 2차원
  matrix = [[1,2,5,8], [2,3,4,9], [4,5,6,7]]
  np.array(matrix, int ).shape
- Tensor 3차원 이상
  tensor = [[[1,2,5,8], [2,3,4,9], [4,5,6,7]],
[[1,2,5,8], [2,3,4,9], [4,5,6,7]],
[[1,2,5,8], [2,3,4,9], [4,5,6,7]],
[[1,2,5,8], [2,3,4,9], [4,5,6,7]]]
  np.array
(tensor, int ).shape

In [9]:
# Vector(1차원) 
# test_array= np.array ([1, 4, 5, 8], dtype=)
vec = np.array([1,4,5,8])    #vec = vector
vec.shape


(4,)

In [11]:
# Matrix 2차원
# matrix = [[1,2,5,8], [2,3,4,9], [4,5,6,7]]
# np.array(matrix, int ).shape
matrix = np.array([[1,2,3],[4,5,16]])
print(matrix.shape)
print(matrix)

(2, 3)
[[ 1  2  3]
 [ 4  5 16]]


In [12]:
# Tensor 3차원 이상 np.array(tensor, int ).shape
tensor = np.array([[[],[]],[[],[]],[[],[]]])

In [13]:
tensor = np.arange(1,25).reshape(2,3,4)
print(tensor)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [14]:
tensor.shape

(2, 3, 4)

In [19]:
vec.shape, matrix.shape, tensor.shape

((4,), (2, 3), (2, 3, 4))

In [20]:
# element 의 갯수 (2차원 이상은 행열평면 곱한 값)
vec.size, matrix.size, tensor.size

(4, 6, 24)

In [21]:
# data type
# float type
# float type


a = np.array([1,2,3], dtype=np.float32)    #dtype=는 빼도됨
a

array([1., 2., 3.], dtype=float32)

In [22]:
b = np.array([1,2,3], dtype=np.int16)
b

array([1, 2, 3], dtype=int16)

### Reshape

- Array 의 shape 을 변경함 (element 의 개수는 동일)
- Array 의 size 만 같다면 다차원으로 자유로이 변형가능
- '-1'은 사이즈가 동일하면 numpy가 알아서 맞춰라는 신호

In [23]:
matrix.shape

(2, 3)

In [24]:
matrix.reshape(6,)

array([ 1,  2,  3,  4,  5, 16])

In [25]:
matrix.reshape(3,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5, 16]])

In [26]:
matrix.reshape(-1,)   #사이즈가 동일할때 numpy가 알아서 맞춰줌

array([ 1,  2,  3,  4,  5, 16])

In [28]:
matrix.reshape(3,-1).shape

(3, 2)

In [32]:
tensor.reshape(4,-1).shape


(4, 6)

In [38]:
matrix.reshape(-1,)

array([ 1,  2,  3,  4,  5, 16])

In [37]:
matrix.reshape(1,-1)

array([[ 1,  2,  3,  4,  5, 16]])

In [40]:
matrix.reshape(-1,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [16]])

### Flatten

- 다차원 array 를 1 차원 array 로 변환

In [50]:
tensor.reshape(-1,)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [42]:
tensor.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

x1 x2 x3               w1 w2 w3
                               (w=weight)

y = WX + b (bias)

w1x1 + w2x2 + w3x3

dot product
(m,n) (n,r)  => (m,r)



## 3. Indexing & Slicing

Indexing

In [43]:
matrix

array([[ 1,  2,  3],
       [ 4,  5, 16]])

In [44]:
matrix[0][1]

2

In [49]:
matrix[1,2]

16

In [52]:
tensor

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [51]:
tensor[1,1,2]

19

### Slicing

In [53]:
b = np.arange(16).reshape(4,-1)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [54]:
# 5,6,9,10
b[1:3, 1:3]

array([[ 5,  6],
       [ 9, 10]])

In [55]:
#5,6,7  9,10,11
b[1:3,1:]

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [57]:
# 1,3,9,11

b[::2,1::2]


array([[ 1,  3],
       [ 9, 11]])

In [59]:
#2차원 이상은 대문자, 1차원은 소문자
# X는 앞에 3열, y는 마지막열

X, y = b[:,:-1], b[:,-1] 
X.shape, y.shape  


((4, 3), (4,))