# DataFrame class

* 시리즈가 여러개 묶여있는 형태
* 열! 위주임 열을 먼저 선택후 몇번째 행이냐가 선택

In [18]:
import numpy as np
import pandas as pd

## 생성

* 데이터를 딕셔너리 형태로 주면, 데이터의 키값이 열이된다
* colunms 는 2차원으로 되어 있음

In [27]:
data = {
    "2015": [9904312, 3448737, 2890451, 2466052],
    "2010": [9631482, 3393191, 2632035, 2431774],
    "2005": [9762546, 3512547, 2517680, 2456016],
    "2000": [9853972, 3655437, 2466338, 2473990],
    "지역": ["수도권", "경상권", "수도권", "경상권"],
    "2010-2015 증가율": [0.0283, 0.0163, 0.0982, 0.0141]
}
columns = ["지역", "2015", "2010", "2005", "2000", "2010-2015 증가율"]
index = ["서울", "부산", "인천", "대구"]
df = pd.DataFrame(data, index=index, columns=columns)
df

지역     2015     2010     2005     2000  2010-2015 증가율
서울  수도권  9904312  9631482  9762546  9853972         0.0283
부산  경상권  3448737  3393191  3512547  3655437         0.0163
인천  수도권  2890451  2632035  2517680  2466338         0.0982
대구  경상권  2466052  2431774  2456016  2473990         0.0141

In [20]:
data = np.arange(24).reshape(4,6)
columns = ["지역", "2015", "2010", "2005", "2000", "2010-2015 증가율"]
index = ["서울", "부산", "인천", "대구"]
df = pd.DataFrame(data, index=index, columns=columns)
df

지역  2015  2010  2005  2000  2010-2015 증가율
서울   0     1     2     3     4              5
부산   6     7     8     9    10             11
인천  12    13    14    15    16             17
대구  18    19    20    21    22             23

In [28]:
df.지역.values    #numpy array

array(['수도권', '경상권', '수도권', '경상권'], dtype=object)

In [29]:
df['2015'].values

array([9904312, 3448737, 2890451, 2466052])

In [30]:
df.columns

Index(['지역', '2015', '2010', '2005', '2000', '2010-2015 증가율'], dtype='object')

In [31]:
df.index.name = '도시'
df.columns.name = '특성'
df

특성   지역     2015     2010     2005     2000  2010-2015 증가율
도시                                                        
서울  수도권  9904312  9631482  9762546  9853972         0.0283
부산  경상권  3448737  3393191  3512547  3655437         0.0163
인천  수도권  2890451  2632035  2517680  2466338         0.0982
대구  경상권  2466052  2431774  2456016  2473990         0.0141

In [32]:
# 전치
df.T

도시                  서울       부산       인천       대구
특성                                               
지역                 수도권      경상권      수도권      경상권
2015           9904312  3448737  2890451  2466052
2010           9631482  3393191  2632035  2431774
2005           9762546  3512547  2517680  2456016
2000           9853972  3655437  2466338  2473990
2010-2015 증가율   0.0283   0.0163   0.0982   0.0141

## 열 데티어의 갱신, 추가, 삭제

In [34]:
df['2010-2015 증가율'] = df['2010-2015 증가율'] * 100
df

특성   지역     2015     2010     2005     2000  2010-2015 증가율
도시                                                        
서울  수도권  9904312  9631482  9762546  9853972          283.0
부산  경상권  3448737  3393191  3512547  3655437          163.0
인천  수도권  2890451  2632035  2517680  2466338          982.0
대구  경상권  2466052  2431774  2456016  2473990          141.0

In [35]:
df['2020'] = [1,2,3,4]
df

특성   지역     2015     2010     2005     2000  2010-2015 증가율  2020
도시                                                              
서울  수도권  9904312  9631482  9762546  9853972          283.0     1
부산  경상권  3448737  3393191  3512547  3655437          163.0     2
인천  수도권  2890451  2632035  2517680  2466338          982.0     3
대구  경상권  2466052  2431774  2456016  2473990          141.0     4

In [36]:
del df['2020']

In [37]:
df

특성   지역     2015     2010     2005     2000  2010-2015 증가율
도시                                                        
서울  수도권  9904312  9631482  9762546  9853972          283.0
부산  경상권  3448737  3393191  3512547  3655437          163.0
인천  수도권  2890451  2632035  2517680  2466338          982.0
대구  경상권  2466052  2431774  2456016  2473990          141.0

##  열 인덱싱

In [38]:
df['지역']      # 결과는 Series

도시
서울    수도권
부산    경상권
인천    수도권
대구    경상권
Name: 지역, dtype: object

In [39]:
df[['지역','2015']]     # 결과는 Dataframe

특성   지역     2015
도시              
서울  수도권  9904312
부산  경상권  3448737
인천  수도권  2890451
대구  경상권  2466052

In [40]:
df[['지역']]     # 결과는 Dataframe

특성   지역
도시     
서울  수도권
부산  경상권
인천  수도권
대구  경상권

In [41]:
type(df['지역']), type(df[['지역']])

(pandas.core.series.Series, pandas.core.frame.DataFrame)

## 행인덱싱

* 항상 슬라이싱(slicing) - 잘 안씀
* df.head()  - 더 자주 씀
* df.tail()

In [43]:
df[1:3]     #3은 포함안함

특성   지역     2015     2010     2005     2000  2010-2015 증가율
도시                                                        
부산  경상권  3448737  3393191  3512547  3655437          163.0
인천  수도권  2890451  2632035  2517680  2466338          982.0

In [45]:
df['부산': '인천']      #인천 포함

특성   지역     2015     2010     2005     2000  2010-2015 증가율
도시                                                        
부산  경상권  3448737  3393191  3512547  3655437          163.0
인천  수도권  2890451  2632035  2517680  2466338          982.0

In [46]:
 df.head(3)
 df.tail(3)

특성   지역     2015     2010     2005     2000  2010-2015 증가율
도시                                                        
부산  경상권  3448737  3393191  3512547  3655437          163.0
인천  수도권  2890451  2632035  2517680  2466338          982.0
대구  경상권  2466052  2431774  2456016  2473990          141.0

## 개별 데이터 인텍싱

- df['열이름']['행이름']

In [47]:
df['2015']['서울']

9904312

In [48]:
df['2015'][0]

9904312

In [59]:
# 연습문제 4.1.3

data = {
    "국어": [80, 90, 70, 30],
    "영어": [90, 70, 60, 40],
    "수학": [90, 60, 80, 70],
}
columns = ["국어", "영어", "수학"]
index = ["춘향", "몽룡", "향단", "방자"]
df = pd.DataFrame(data, index=index, columns=columns)
df

국어  영어  수학
춘향  80  90  90
몽룡  90  70  60
향단  70  60  80
방자  30  40  70

In [51]:
#(1) 모든 학생의 수학 점수를 시리즈로 나타낸다.
df['수학']   # df.수학도 된다

춘향    90
몽룡    60
향단    80
방자    70
Name: 수학, dtype: int64

In [56]:
df.수학

춘향    90
몽룡    60
향단    80
방자    70
Name: 수학, dtype: int64

In [55]:
#(2) 모든 학생의 국어와 영어 점수를 데이터 프레임으로 나타낸다.
df[['국어', '영어']]

국어  영어
춘향  80  90
몽룡  90  70
향단  70  60
방자  30  40

In [61]:
#(3) 모든 학생의 각 과목 평균 점수를 새로운 열로 추가한다.
df.values

array([[80, 90, 90],
       [90, 70, 60],
       [70, 60, 80],
       [30, 40, 70]])

In [62]:
np.mean(df.values, axis=1).round(1)

array([86.7, 73.3, 70. , 46.7])

In [76]:
df['평균'] = np.mean(df.values, axis=1).round(1)
df

국어  영어  수학    평균
춘향  80  90  90  86.7
몽룡  90  70  60  73.3
향단  70  60  80  70.0
방자  30  80  70  60.0

In [64]:
df.mean(axis=1)

춘향    86.675
몽룡    73.325
향단    70.000
방자    46.675
dtype: float64

In [77]:
# (4) 방자의 영어 점수를 80점으로 수정하고 평균 점수도 다시 계산한다.
del df['평균']
df['영어'][3]  = 80
df['평균'] = np.round(df.mean(axis=1),1)
df

국어  영어  수학    평균
춘향  80  90  90  86.7
몽룡  90  70  60  73.3
향단  70  60  80  70.0
방자  30  80  70  60.0

In [78]:
#(5) 춘향의 점수를 데이터프레임으로 나타낸다.
df[:'춘향']

국어  영어  수학    평균
춘향  80  90  90  86.7

In [79]:
df.head(1)

국어  영어  수학    평균
춘향  80  90  90  86.7

In [80]:
df.T[['춘향']]

춘향
국어  80.0
영어  90.0
수학  90.0
평균  86.7

In [81]:
# 중간에 있는 두 행 꺼내오기
df.head(3).tail(2)

국어  영어  수학    평균
몽룡  90  70  60  73.3
향단  70  60  80  70.0

In [82]:
# (6) 향단의 점수를 시리즈로 나타낸다.
df.T['향단']

국어    70.0
영어    60.0
수학    80.0
평균    70.0
Name: 향단, dtype: float64